### ISSUE TITLE
Question not issue

### ISSUE THREAD

**Issue by redg25** [Abhishek-op/SR#1]
Hi, well done with your SR. I am trying to understand why the listener stops after about 5s when nothing is said. I read that there was no maximum time for the Android listener and I don't see anythimg in your code that set this logic.   Thanks in advance for your explanation.

**Comment by Abhishek-op** [comment]
Hi, Sorry for the late reply. The speech endpoint will automatically stop the recognizer from listening when it determines the speech has completed and provide results. This API is not intended to be used for continuous recognition, which would consume a significant amount of battery and bandwidth. 
For reference: 
1. https://developer.android.com/reference/android/speech/SpeechRecognizer
2. https://developer.android.com/reference/android/speech/SpeechRecognizer#stopListening()
have a look at these references
If you need continuous speech recognition then here is a way if we use third-party hot word detection. I am working on it.

**Comment by redg25** [comment]
Thank you Abhishek,
It makes things clearer. I would like to build an app that can interact with a chess engine only with voice so I can play blind chess when going for a run. So yes, I need the listener to stay on for the time the user search for his move.
For now, if the listener stops and there are no results yet, I simply restart the listener and it seems to work. But as it is mentioned in the doc, it surely consumes a lot
I will keep an eye on your continuous speech recognition work. Thanks again for the explanation




    Le mercredi 19 mai 2021, 11:39:58 UTC+2, Abhishek-op ***@***.***> a écrit :  
 
 


Hi, Sorry for the late reply. The speech endpoint will automatically stop the recognizer from listening when it determines the speech has completed and provide results. This API is not intended to be used for continuous recognition, which would consume a significant amount of battery and bandwidth.
For reference:
   
   - https://developer.android.com/reference/android/speech/SpeechRecognizer
   - https://developer.android.com/reference/android/speech/SpeechRecognizer#stopListening()   
have a look at these references   
If you need continuous speech recognition then here is a way for continuous speech recognition if we use third-party hot word detection. I am working on it.
