### ISSUE TITLE
Why it says "Is Supported: False" ?

### ISSUE THREAD

**Issue by codinghedgehog-python** [Abhishek-op/SR#4]
Hi Abhishek,
I'd like to use your code for my own project (why reinvent the wheel) and when I build it for my Android
it says at the top "Is Supported: False". Does it mean that certain Android version won't run it ? My test device
runs Android 8 (Oreo). I checked the source code but it's not obvious from the code why it shows False.
Do I need newer version of Android for it to work ?

**Comment by Abhishek-op** [comment]
Hi,
Sorry for the late reply. Check that the 'google' application is installed in your system or not. It may be the cause of the problem because Speech recognition requires any application that provides an `android.speech.RecognitionService` and 'google' application provides this service.

**Comment by codinghedgehog-python** [comment]
Hi Abhishek, you were right. The Google app on the phone was disabled. Once I reenabled it the label changed to `True`.
I'm closing this with thanks !
