### ISSUE TITLE
Not an issue, rather question

### ISSUE THREAD

**Issue by codinghedgehog-python** [Abhishek-op/SR#5]
Abhishek, in which case the program will throw "NotImplemented" exception ? It's not very clear from the source code.
I had it working yesterday but today I'm getting the exception.

From traceback I can see that exception is being triggered by this private method:
```
def _start(self):
        raise NotImplementedError
```

Thank you for clearing things up for me.

**Comment by Abhishek-op** [comment]
When you'll use private methods `stt._start, stt._exist, and stt._stop` then the program will throw `NotImplementedError`.  Instead of this, you should have to use the public methods `stt.start, stt.exist, stt.stop`.

**Comment by codinghedgehog-python** [comment]
I understand people aren't supposed to call the private methods as it'll raise an exception. I'm calling `stt.start()` and
it throws that exception. Strange is that it didn't do it couple of days back and I didn't change the code.

**Comment by Abhishek-op** [comment]
Can you paste here logs.

**Comment by codinghedgehog-python** [comment]
> Can you paste here logs what are you getting.

```
06-12 10:45:08.550 15771 15903 I python  :    File "/home/mark/off_android/.buildozer/android/app/Speechrecognizer/facades/stt.py", line 71, in start
06-12 10:45:08.552 15771 15903 I python  :    File "/home/mark/off_android/.buildozer/android/app/Speechrecognizer/facades/stt.py", line 85, in _start
06-12 10:45:08.553 15771 15903 I python  :  NotImplementedError
06-12 10:45:08.553 15771 15903 I python  : Python for android ended.
```
the error originates from this block:
```
on_and_off_btn = self.ids['on_and_off_btn']
stt.start()
self.inactive = False
Clock.schedule_once(self.stop_listening, 7)
```
See I'm not calling private methods anywhere.

**Comment by Abhishek-op** [comment]
I am unable to understand why it is happening. try one thing go to `Speechrecognizer/facades/stt.py` and remove all private methods than try to build.

**Comment by codinghedgehog-python** [comment]
To be fair you're calling the private method within `start()`:
```
# public methods
    def start(self):
        '''
        Start listening.
        '''

        self.results = []
        self.partial_results = []
        self._start()
        self.listening = True
```
but it wasn't an issue until now.

**Comment by Abhishek-op** [comment]
I restricted the `_start()` method by `notImplementedError` because if someone uses it then the program will not work properly. but now it becomes an issue. I tried many ways and I find that removing all private methods from `Speechrecognizer/facades/stt.py` can help you.
